# Generated by Django 5.2.7 on 2025-11-02 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное название')),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое название')),
                ('director', models.CharField(max_length=100, verbose_name='Имя директора')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('health_status', models.CharField(max_length=100, verbose_name='Состояние здоровья')),
                ('family_status', models.CharField(max_length=100, verbose_name='Статус семьи')),
                ('note', models.CharField(max_length=500, verbose_name='Примечание')),
                ('education_class', models.IntegerField(verbose_name='Номер класса')),
                ('birthday', models.DateTimeField(verbose_name='Дата рождения')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='children.school')),
            ],
        ),
    ]
