# Generated by Django 5.2.7 on 2025-11-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['last_name'], 'verbose_name': 'Учащийся', 'verbose_name_plural': 'Учащиеся'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['full_name'], 'verbose_name': 'Школа', 'verbose_name_plural': 'Школы'},
        ),
    ]
