# Generated by Django 5.2.7 on 2025-11-15 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPermissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_managed', models.BooleanField(default=True, help_text='Включить управление разрешениями для этой модели', verbose_name='Управление разрешениями')),
                ('auto_create_permissions', models.BooleanField(default=True, help_text='Автоматически создавать CRUD разрешения', verbose_name='Автосоздание разрешений')),
                ('content_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Конфигурация модели',
                'verbose_name_plural': 'Конфигурации моделей',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название разрешения')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Кодовое имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='contenttypes.contenttype', verbose_name='Тип контента')),
            ],
            options={
                'verbose_name': 'Разрешение',
                'verbose_name_plural': 'Разрешения',
                'unique_together': {('codename', 'content_type')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_global', models.BooleanField(default=False, help_text='Роль применяется ко всем объектам', verbose_name='Глобальная роль')),
                ('permissions', models.ManyToManyField(blank=True, to='permissions.permission', verbose_name='Разрешения')),
                ('users', models.ManyToManyField(blank=True, related_name='custom_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Роль пользователя',
                'verbose_name_plural': 'Роли пользователей',
            },
        ),
        migrations.CreateModel(
            name='ObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Время выдачи')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Кем выдано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.permission', verbose_name='Разрешение')),
            ],
            options={
                'verbose_name': 'Разрешение на объект',
                'verbose_name_plural': 'Разрешения на объекты',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='permissions_content_8a3d19_idx')],
                'unique_together': {('permission', 'user', 'content_type', 'object_id')},
            },
        ),
    ]
